
import 'package:task/data/db.dart';

abstract class Func {
  static returnDistrict(String region) {
    switch (region) {
      case "Namangan":
        return MyDB.namangan;
      case "Qoraqalpog`iston":
        return MyDB.qoraqalpogiston;
      case "Xorazm":
        return MyDB.xorazm;
      case "Navoiy":
        return MyDB.navoiy;
      case "Buxoro":
        return MyDB.buxoro;
      case "Samarqand":
        return MyDB.samarqand;
      case "Qashqadaryo":
        return MyDB.qashqadaryo;
      case "Surxondaryo":
        return MyDB.surxondaryo;
      case "Jizzax":
        return MyDB.jizzax;
      case "Sirdaryo":
        return MyDB.sirdaryo;
      case "Toshkent":
        return MyDB.toshkent;
      case "Farg`ona":
        return MyDB.fargona;
      case "Andijon":
        return MyDB.andijon;
      case "Toshkent sh":
        return MyDB.toshkentsh;
    }
  }

  static returnRId(String name) {
    switch (name) {
      case "Namangan":
        return 1;
      case "Qoraqalpog`iston":
        return 2;
      case "Xorazm":
        return 3;
      case "Navoiy":
        return 4;
      case "Buxoro":
        return 5;
      case "Samarqand":
        return 6;
      case "Qashqadaryo":
        return 7;
      case "Surxondaryo":
        return 8;
      case "Jizzax":
        return 9;
      case "Sirdaryo":
        return 10;
      case "Toshkent":
        return 11;
      case "Farg`ona":
        return 12;
      case "Andijon":
        return 13;
      case "Toshkent sh":
        return 15;
    }
  }

  static returnDId(String name) {
    switch (name) {
      case "Chortoq":
        return 2;
      case "Chust":
        return 3;
      case "Kosonsoy":
        return 4;
      case "Mingbuloq":
        return 5;
      case "Namangan":
        return 6;
      case "Norin":
        return 7;
      case "Pop":
        return 8;
      case "To`raqo`rg`on":
        return 9;
      case "Uchqo`rg`on":
        return 10;
      case "Uychi":
        return 11;
      case "Yangiqo`rg`on":
        return 12;
      case "Amudaryo":
        return 13;
      case "Beruniy":
        return 14;
      case "Chimboy":
        return 15;
      case "Ellikqal`a":
        return 16;
      case "Kegeyli":
        return 17;
      case "Mo`ynoq":
        return 19;
      case "Shumanay":
        return 20;
      case "Nukus":
        return 21;
      case "Qonliko`l":
        return 22;
      case "Qo`ng`irot":
        return 23;
      case "Qorao`zak":
        return 24;
      case "Taxtako`pir":
        return 25;
      case "To`rtko`l":
        return 26;
      case "Xo`jayli":
        return 27;
      case "Bogot":
        return 28;
      case "Gurlen":
        return 29;
      case "Xonqa":
        return 30;
      case "Hazorasp":
        return 31;
      case "32":
        return 24;
      case "Qo`shko`pir":
        return 33;
      case "Shovot":
        return 34;
      case "Urganch":
        return 35;
      case "Yangiariq":
        return 36;
      case "Yangibozor":
        return 37;
      case "Kanimex":
        return 38;
      case "Navoiy":
        return 39;
      case "Qiziltepa":
        return 40;
      case "Xatirchi":
        return 41;
      case "Navbahor":
        return 42;
      case "Nurota":
        return 43;
      case "Tamdi":
        return 44;
      case "Uchquduq":
        return 45;
      case "Olot":
        return 46;
      case "Buxoro":
        return 47;
      case "G`ijduvon":
        return 48;
      case "Jondor":
        return 49;
      case "Kogon":
        return 50;
      case "Qorako`l":
        return 51;
      case "Qorovulbozor":
        return 52;
      case "Peshku":
        return 53;
      case "Romitan":
        return 54;
      case "Shofirkon":
        return 55;
      case "Vabkent":
        return 56;
      case "Bulung`ur":
        return 57;
      case "Ishtixon":
        return 58;
      case "Jomboy":
        return 59;
      case "Kattaqo`rg`on":
        return 60;
      case "Qo`shrabot":
        return 61;
      case "Narpay":
        return 62;
      case "Nurobod":
        return 63;
      case "Oqdaryo":
        return 64;
      case "Paxtachi":
        return 65;
      case "Payariq":
        return 66;
      case "Pastdarg`om":
        return 67;
      case "Samarqand":
        return 68;
      case "Toyloq":
        return 69;
      case "Urgut":
        return 70;
      case "Chiroqchi":
        return 71;
      case "Dehqonobod":
        return 72;
      case "G`uzor":
        return 73;
      case "Qamashi":
        return 74;
      case "Qarshi":
        return 75;
      case "Koson":
        return 76;
      case "Kasbi":
        return 77;
      case "Kitob":
        return 78;
      case "Mirishkor":
        return 79;
      case "Muborak":
        return 80;
      case "Nishon":
        return 81;
      case "Shahrisabz":
        return 82;
      case "Yakkabog`":
        return 83;
      case "Angor":
        return 84;
      case "Bandixon":
        return 85;
      case "Boysun":
        return 86;
      case "Denov":
        return 87;
      case "Jarqo`rg`on":
        return 88;
      case "Kizirik":
        return 89;
      case "Qumqo`rg`on":
        return 90;
      case "Muzrabot":
        return 91;
      case "Oltinsoy":
        return 92;
      case "Sariosiyo":
        return 93;
      case "Sherobod":
        return 94;
      case "Sho`rchi":
        return 95;
      case "Termiz":
        return 96;
      case "Uzun":
        return 97;
      case "Arnasoy":
        return 98;
      case "Baxmal":
        return 99;
      case "Do`stlik":
        return 100;
      case "Forish":
        return 101;
      case "G`allaorol":
        return 102;
      case "Jizzax":
        return 103;
      case "Mirzacho`l":
        return 104;
      case "Paxtakor":
        return 105;
      case "Yangiobod":
        return 106;
      case "Zomin":
        return 107;
      case "Zafarobod":
        return 108;
      case "Zarbdar":
        return 109;
      case "Akaltin":
        return 110;
      case "Bayaut":
        return 111;
      case "Guliston":
        return 112;
      case "Xovast":
        return 113;
      case "Mirzaobod":
        return 114;
      case "Sayxunobod":
        return 115;
      case "Sardoba":
        return 116;
      case "Sirdayo":
        return 117;
      case "Bekobod":
        return 118;
      case "Bo`stonliq":
        return 119;
      case "Buka":
        return 120;
      case "Chinoz":
        return 121;
      case "Qibray":
        return 122;
      case "Ohangaron":
        return 123;
      case "Oqqo`rg`on":
        return 124;
      case "Parkent":
        return 125;
      case "Piskent":
        return 126;
      case "Quyi Chirchiq":
        return 127;
      case "O`rta Chirchiq":
        return 128;
      case "Yangi yo`l":
        return 129;
      case "Yuqori Chirchiq":
        return 130;
      case "Zangiata":
        return 131;
      case "Oltiariq":
        return 132;
      case "Bag`dod":
        return 133;
      case "Beshariq":
        return 134;
      case "Buvayda":
        return 135;
      case "Dang`ara":
        return 136;
      case "Farg`ona":
        return 137;
      case "Furqat":
        return 138;
      case "Qo`shtepa":
        return 139;
      case "Quva":
        return 140;
      case "Rishton":
        return 141;
      case "So`x":
        return 142;
      case "Toshloq":
        return 143;
      case "Uchko`prik":
        return 144;
      case "O`zbekiston":
        return 145;
      case "Yozyovon":
        return 146;
      case "Andijon":
        return 147;
      case "Asaka":
        return 148;
      case "Baliqchi":
        return 149;
      case "Boz":
        return 150;
      case "Buloqboshi":
        return 151;
      case "Jalolquduq":
        return 152;
      case "Xo`jaobod":
        return 153;
      case "Kurgontepa":
        return 154;
      case "Marhamat":
        return 155;
      case "Oltinko`l":
        return 156;
      case "Paxtaobod":
        return 157;
      case "Shahrixon":
        return 158;
      case "Ulugnor":
        return 159;
      case "Bektemir":
        return 160;
      case "Chilonzor":
        return 161;
      case "Hamza":
        return 163;
      case "Mirobod":
        return 164;
      case "Mirzo Ulug`bek":
        return 165;
      case "Sergeli":
        return 166;
      case "Shayxontohur":
        return 167;
      case "Olmazar":
        return 168;
      case "Uchtepa":
        return 169;
      case "Yakkasaroy":
        return 170;
      case "Yunusobod":
        return 171;
    }
  }
}
